export const indianStates = [
  {
    name: 'Andhra Pradesh',
    capital: 'Amaravati',
    population: 49386799,
    area: 160205,
    language: 'Telugu',
    imageUrl: 'https://example.com/states/ap.jpg',
  },
  {
    name: 'Arunachal Pradesh',
    capital: 'Itanagar',
    population: 1382611,
    area: 83743,
    language: 'English',
    imageUrl: 'https://example.com/states/ar.jpg',
  },
  {
    name: 'Assam',
    capital: 'Dispur',
    population: 31169272,
    area: 78438,
    language: 'Assamese',
    imageUrl: 'https://example.com/states/as.jpg',
  },
  {
    name: 'Bihar',
    capital: 'Patna',
    population: 103804637,
    area: 94163,
    language: 'Hindi',
    imageUrl: 'https://example.com/states/br.jpg',
  },
  {
    name: 'Chhattisgarh',
    capital: 'Raipur',
    population: 25540196,
    area: 135192,
    language: 'Hindi',
    imageUrl: 'https://example.com/states/cg.jpg',
  },
  {
    name: 'Goa',
    capital: 'Panaji',
    population: 1457723,
    area: 3702,
    language: 'Konkani',
    imageUrl: 'https://example.com/states/ga.jpg',
  },
  {
    name: 'Gujarat',
    capital: 'Gandhinagar',
    population: 60383628,
    area: 196244,
    language: 'Gujarati',
    imageUrl: 'https://example.com/states/gj.jpg',
  },
  {
    name: 'Karnataka',
    capital: 'Bengaluru',
    population: 61095297,
    area: 191791,
    language: 'Kannada',
    imageUrl: 'https://example.com/states/ka.jpg',
  },
  // Add remaining states...
];
